replicaCount: 1

image:
  repository: easytecs/grafana-uptime
  pullPolicy: IfNotPresent
  tag: prod-c48dcec

listServicesToCheck: []
sleepTimeSecond: 15

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000


resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false 
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  server:
    global:
      scrape_interval: 15s
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'grana-uptime'
          static_configs:
            - targets: ['grafana-uptime-svc:8000']
