apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-uptime-data
data:
  payload.yaml: |
    {{- toYaml .Values.listServicesToCheck | nindent 12 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-uptime-params
data:
  SLEEP_TIME_SECOND: "{{ .Values.sleepTimeSecond }}"